name: 'job_market_radar'
version: '1.0.0'
config-version: 2
profile: 'job_market_radar'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  job_market_radar:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
